apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: redeploy
spec:
  version: "v0.0.1"
  homepage: https://github.com/tcoupin/kubectl-redeploy
  shortDescription: "Trigger redeploy of a deployment"
  description: |
     Krew plugin to trigger redeploy of a deployment.
  platforms:
  - selector:
      matchExpressions:
      - key: "os"
        operator: "In"
        values:
        - darwin
        - linux
        - windows
    uri: https://github.com/tcoupin/kubectl-redeploy/archive/v0.0.1.zip
    sha256: 18cb0519980ee19aeef25a1dd2bd337aff56bb6db78ce71f3aa96c0ff9f5e18d
    files:
    - from: "kubectl-redeploy-0.0.1/kubectl-redeploy.sh"
      to: "kubect-redeploy.sh"
    - from: "kubectl-redeploy-0.0.1/LICENSE"
      to: "."
    bin: kubect-redeploy.sh
